# Latest docker-compose version
# refer to: https://docs.docker.com/compose/compose-file/compose-versioning/
version: "3.8"

# Docker volumes are useful to bind local
# folders and directories to the virtual
# file system of containers so that we can
# persist the data that was manipulated
# inside the container during its lifecycle
volumes:
  mariadb_data:
    name: mariadb_data
    driver: local
    driver_opts:
      # Declare as an external volume or a bind mount
      type: none
      # Mount as bind
      o: bind
      #!TODO comment this path and uncomment the one bellow 
      device: /home/kuninoto/data/mariadb_data
      #device: /home/nnuno-ca/data/mariadb_data

  wordpress_data:
    name: wordpress_data
    driver: local
    driver_opts:
      # Declare as an external volume or a bind mount
      type: none
      # Mount as bind
      o: bind
      #!TODO comment this path and uncomment the one bellow
      device: /home/kuninoto/data/wordpress_data
      #device: /home/nnuno-ca/data/wordpress_data


# Docker networks allow containers
# in the same network to communicate
# with each other treating their
# container_names as hostnames
networks:
  inception-network:
    name: inception-network
    driver: bridge

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/.
    image: mariadb
    # bind mariadb_data volume to /var/lib/mysql
    # directory inside the container
    volumes:
      - mariadb_data:/var/lib/mysql
    env_file: .env
    networks:
      - inception-network
    restart: on-failure

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/.
    image: wordpress
    depends_on:
      - mariadb
    init: true
    networks:
      - inception-network
    # bind wordpress_data volume to /var/www/html
    # directory inside the container
    volumes:
      - wordpress_data:/var/www/html
    # Ensure that MariaDB's container up and running
    env_file: .env
    restart: on-failure

  nginx:
    container_name: nginx
    build: ./requirements/nginx/.
    image: nginx
    # port mapping
    ports:
      - 443:443
    depends_on:
      - wordpress
    networks:
      - inception-network
    # bind wordpress_data volume to /var/www/html
    # directory inside the container
    volumes:
      - wordpress_data:/var/www/html
    env_file: .env
    restart: on-failure
